---
- name: Install Spotify
  hosts: rpi
  become: yes
  tasks:
    - name: Update apt cache and packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install necessary packages
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
    - name: Add GPG key for raspotify
      apt_key:
        url: https://dtcooper.github.io/raspotify/key.asc
        state: present
    - name: Add raspotify repository
      apt_repository:
        repo: deb https://dtcooper.github.io/raspotify raspotify main
        state: present
    - name: Download raspotify installation file
      get_url:
        url: "{{ raspotify_deb_url }}"
        dest: /tmp/raspotify.deb
    - name: Install raspotify
      apt:
        deb: /tmp/raspotify.deb
        state: present
    