---
- name: Install Jellyfin
  hosts: jellyfin
  become: true
  roles:
    - name: jellyfin
      tags: jellyfin
    
    - name: prometheus.prometheus.node_exporter
      tags: node_exporter

    - name: print_server
      tags: print_server
    