---
- name: Install Jellyfin
  hosts: jellyfin
  become: true
  roles:
    - name: jellyfin
      tags: jellyfin
    
    - name: prometheus.prometheus.node_exporter
      tags: prometheus

    - name: prometheus
      tags: prometheus

    - name: print_server
      tags: print_server
    
    - name: grafana
      tags: grafana
  post_tasks:
    - name: Add Deluge PPA repo
      ansible.builtin.apt_repository:
        repo: ppa:deluge-team/stable
        state: present
    
    - name: Apt update
      ansible.builtin.apt:
        update_cache: true

    - name: Install additional packages
      ansible.builtin.package:
        name:
          - deluged 
          - deluge-web 
          - deluge-console