---
- name: Install Pi Hole
  hosts: rpi
  become: true
  pre_tasks:
    - name: Configure static ip
      community.general.nmcli:
        conn_name: "Wired connection 1"
        state: present
        ip4:
          - "192.168.0.10/24"
        gw4: 192.168.0.1
        dns4:
          - "8.8.8.8"
          - "8.8.4.4"
        state: present
  roles:
    - rpihole
    - prometheus.prometheus.node_exporter
    
    